import { useState, useEffect, useRef, useMemo } from 'react'
import { jobsAPI, agentsAPI, mcpAPI } from '../lib/api'
import { getToolAccessBadge } from '../lib/mcpToolAccess'
import { buildIndependentSharedToolWarning } from '../lib/independentWorkflowSharedTools'
import { filterByJobAllowedIds, jobHasExplicitMcpScope } from '../lib/jobMcpScope'
import type { Agent } from '../lib/types'
import type { Job } from '../lib/types'
import type { MCPToolConfigRes, MCPServerConnectionRes } from '../lib/api'

interface WorkflowBuilderProps {
  jobId: number
  onWorkflowCreated: () => void
  initialSelectedAgentIds?: number[]
  /** Job data (optional); if provided, used for job-level allowed tools and step tool pool */
  job?: Job | null
}

export type WorkflowCollaborationMode = 'from_brd' | 'independent' | 'sequential'

export type ToolVisibility = 'full' | 'names_only' | 'none'

/** Per-step tool assignment: agent_index -> { platformIds, connectionIds, toolVisibility?, taskType? } */
type StepToolSelection = Record<
  number,
  { platformIds: number[]; connectionIds: number[]; toolVisibility?: ToolVisibility; taskType?: string }
>

type StepToolsUpdateOpts = { taskType?: string }

const DEFAULT_OUTPUT_CONTRACT = {
  version: '1.0',
  format: 'sandhi_universal_json',
  _description: 'Universal contract template for any domain. Replace sample placeholders with your business fields.',
  record_schema: {
    _description: 'Describe the structure of ONE output record generated by agents.',
    _fields_help: {
      record_id: 'Unique identifier for one output record.',
      subject_id: 'Business entity ID (customer, claim, invoice, device, etc.).',
      subject_type: 'Entity category relevant to your domain.',
      outcome: 'Final decision/classification/result produced by workflow.',
      confidence_score: 'Optional numeric confidence between 0 and 1.',
      reasons: 'Optional list of short reason strings for traceability.',
      attributes: 'Domain-specific structured payload for additional output fields.',
      evidence_refs: 'Optional references to source data/files used for this result.',
      generated_at: 'ISO timestamp when the record was generated.',
    },
    record_id: '<string>',
    subject_id: '<string>',
    subject_type: '<string>',
    outcome: '<string>',
    confidence_score: '<number_0_to_1_optional>',
    reasons: ['<string_optional>'],
    attributes: {
      '<domain_field_1>': '<value>',
      '<domain_field_2>': '<value>',
    },
    evidence_refs: [
      {
        source: '<system_or_dataset_name>',
        pointer: '<path_or_table_or_row_reference>',
      },
    ],
    generated_at: '<iso_datetime>',
  },
  write_policy: {
    _description: 'How multi-target writes behave when one or more targets fail.',
    _fields_help: {
      on_write_error: "Use 'continue' to attempt all targets, or 'stop' to halt on first failure.",
      min_successful_targets: 'Minimum number of successful write targets required for overall success.',
    },
    on_write_error: 'continue',
    min_successful_targets: 1,
  },
  write_targets: [
    {
      _description: 'One destination for final output write.',
      tool_name: '<platform_write_tool_name>',
      target: {
        target_type: '<database|object_storage|warehouse|vector_db>',
        name: '<target_identifier>',
      },
      write_mode: '<append|overwrite|upsert|merge>',
      merge_keys: ['<primary_or_business_key_optional>'],
      options: {
        '<option_name_optional>': '<option_value>',
      },
    },
  ],
}

function outputContractFromJobPayload(job: Job | null | undefined): Record<string, unknown> | null {
  if (!job?.output_contract) return null
  const c = job.output_contract
  if (typeof c === 'string') {
    try {
      const p = JSON.parse(c) as unknown
      return p && typeof p === 'object' && !Array.isArray(p) ? (p as Record<string, unknown>) : null
    } catch {
      return null
    }
  }
  if (typeof c === 'object' && !Array.isArray(c)) return c as Record<string, unknown>
  return null
}

export function WorkflowBuilder({ jobId, onWorkflowCreated, initialSelectedAgentIds, job }: WorkflowBuilderProps) {
  const [selectedAgents, setSelectedAgents] = useState<number[]>(initialSelectedAgentIds ?? [])
  const [availableAgents, setAvailableAgents] = useState<Agent[]>([])
  const [platformTools, setPlatformTools] = useState<MCPToolConfigRes[]>([])
  const [connections, setConnections] = useState<MCPServerConnectionRes[]>([])
  const [stepToolSelections, setStepToolSelections] = useState<StepToolSelection>({})
  const stepToolSelectionsRef = useRef<StepToolSelection>({})
  const [jobToolVisibility, setJobToolVisibility] = useState<ToolVisibility>('full')
  const [mode, setMode] = useState<'auto' | 'manual'>('auto')
  const [workflowCollaboration, setWorkflowCollaboration] = useState<WorkflowCollaborationMode>('from_brd')
  const [writeExecutionMode, setWriteExecutionMode] = useState<'platform' | 'agent' | 'ui_only'>('platform')
  const [outputArtifactFormat, setOutputArtifactFormat] = useState<'jsonl' | 'json'>('jsonl')
  const [outputContractText, setOutputContractText] = useState(JSON.stringify(DEFAULT_OUTPUT_CONTRACT, null, 2))
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState('')

  useEffect(() => {
    stepToolSelectionsRef.current = stepToolSelections
  }, [stepToolSelections])

  useEffect(() => {
    loadAgents()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [initialSelectedAgentIds])

  useEffect(() => {
    loadTools()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [jobId, job?.id, job?.allowed_platform_tool_ids, job?.allowed_connection_ids])

  useEffect(() => {
    if (initialSelectedAgentIds && initialSelectedAgentIds.length > 0) {
      setSelectedAgents(initialSelectedAgentIds)
    }
  }, [initialSelectedAgentIds])

  useEffect(() => {
    if (!job?.id) return
    if (
      job.write_execution_mode === 'agent' ||
      job.write_execution_mode === 'platform' ||
      job.write_execution_mode === 'ui_only'
    ) {
      setWriteExecutionMode(job.write_execution_mode)
    }
    if (job.output_artifact_format === 'json' || job.output_artifact_format === 'jsonl') {
      setOutputArtifactFormat(job.output_artifact_format)
    }
    const contract = outputContractFromJobPayload(job)
    if (contract) {
      setOutputContractText(JSON.stringify(contract, null, 2))
    }
  }, [job?.id, job?.write_execution_mode, job?.output_artifact_format, job?.output_contract])

  // Sync job-level tool visibility from API (including 'none'; do not use truthy check on the string).
  useEffect(() => {
    if (!job?.id) return
    const tv = job.tool_visibility
    if (tv === 'full' || tv === 'names_only' || tv === 'none') {
      setJobToolVisibility(tv)
    } else {
      setJobToolVisibility('full')
    }
  }, [job?.id, job?.tool_visibility])

  // When job has workflow steps, pre-fill step tool selections from saved state (by step order)
  useEffect(() => {
    const jobData = job ?? null
    const steps = jobData?.workflow_steps
    if (!steps?.length || selectedAgents.length === 0) return
    // Steps are ordered by step_order; index i = step_order - 1
    const next: StepToolSelection = {}
    steps.forEach((step, i) => {
      const rawVis = step.tool_visibility as ToolVisibility | undefined
      const toolVisibility =
        rawVis === 'full' || rawVis === 'names_only' || rawVis === 'none' ? rawVis : undefined
      let platformIds = step.allowed_platform_tool_ids ?? []
      let connectionIds = step.allowed_connection_ids ?? []
      if (toolVisibility === 'none') {
        platformIds = []
        connectionIds = []
      }
      next[i] = { platformIds, connectionIds, toolVisibility }
    })
    setStepToolSelections((prev) => {
      // Only overwrite when we have steps and prev is empty or we're initializing from job
      if (Object.keys(prev).length === 0) return next
      return prev
    })
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [job?.id, job?.workflow_steps, selectedAgents.length])

  /** After a job has run, keep agent list aligned with saved workflow steps when opening this screen. */
  useEffect(() => {
    if (!job?.workflow_steps?.length || job.status === 'draft') return
    const ids = [...new Set(job.workflow_steps.map((s) => s.agent_id))]
    if (ids.length) setSelectedAgents(ids)
  }, [job?.id, job?.status, job?.workflow_steps])

  const workflowLocked = !!(job?.status && job.status !== 'draft')

  const independentSharedToolWarning = useMemo(
    () =>
      buildIndependentSharedToolWarning({
        collaborationMode: workflowCollaboration,
        selectedAgentCount: selectedAgents.length,
        stepToolSelections: selectedAgents.map((_, idx) => {
          const s = stepToolSelections[idx] ?? { platformIds: [], connectionIds: [] }
          return { platformIds: s.platformIds, connectionIds: s.connectionIds }
        }),
        jobAllowedPlatformIds: job?.allowed_platform_tool_ids,
        jobAllowedConnectionIds: job?.allowed_connection_ids,
      }),
    [
      workflowCollaboration,
      selectedAgents,
      stepToolSelections,
      job?.allowed_platform_tool_ids,
      job?.allowed_connection_ids,
    ]
  )

  const loadAgents = async () => {
    try {
      const agents = await agentsAPI.list('active')
      if (initialSelectedAgentIds && initialSelectedAgentIds.length > 0) {
        setAvailableAgents(agents.filter((a: Agent) => initialSelectedAgentIds!.includes(a.id)))
      } else {
        setAvailableAgents(agents)
      }
    } catch (error) {
      console.error('Failed to load agents:', error)
    }
  }

  const loadTools = async () => {
    try {
      const [tools, conns] = await Promise.all([mcpAPI.listTools(), mcpAPI.listConnections()])
      const jobData = job ?? (jobId ? await jobsAPI.get(jobId).catch(() => null) : null)
      const allowedPlatform = jobData?.allowed_platform_tool_ids
      const allowedConn = jobData?.allowed_connection_ids
      setPlatformTools(filterByJobAllowedIds(tools, allowedPlatform))
      setConnections(filterByJobAllowedIds(conns, allowedConn))
    } catch (error) {
      console.error('Failed to load tools:', error)
    }
  }

  const setStepTools = (
    agentIndex: number,
    platformIds: number[],
    connectionIds: number[],
    toolVisibility?: ToolVisibility,
    opts?: StepToolsUpdateOpts
  ) => {
    setStepToolSelections((prev) => {
      const prevSel = prev[agentIndex]
      let taskType = prevSel?.taskType
      if (opts && 'taskType' in opts) {
        const t = opts.taskType?.trim()
        taskType = t || undefined
      }
      const next = {
        ...prev,
        [agentIndex]: {
          platformIds,
          connectionIds,
          toolVisibility,
          ...(taskType ? { taskType } : {}),
        },
      }
      stepToolSelectionsRef.current = next
      return next
    })
  }

  const stepEffectiveToolVisibility = (agentIndex: number): ToolVisibility => {
    const cur = stepToolSelections[agentIndex]
    return cur?.toolVisibility ?? jobToolVisibility
  }

  const toggleStepPlatformTool = (agentIndex: number, toolId: number) => {
    if (stepEffectiveToolVisibility(agentIndex) === 'none') return
    const cur = stepToolSelections[agentIndex] ?? { platformIds: [], connectionIds: [] }
    const platformIds = cur.platformIds.includes(toolId)
      ? cur.platformIds.filter((id) => id !== toolId)
      : [...cur.platformIds, toolId]
    setStepTools(agentIndex, platformIds, cur.connectionIds, cur.toolVisibility)
  }

  const toggleStepConnection = (agentIndex: number, connId: number) => {
    if (stepEffectiveToolVisibility(agentIndex) === 'none') return
    const cur = stepToolSelections[agentIndex] ?? { platformIds: [], connectionIds: [] }
    const connectionIds = cur.connectionIds.includes(connId)
      ? cur.connectionIds.filter((id) => id !== connId)
      : [...cur.connectionIds, connId]
    setStepTools(agentIndex, cur.platformIds, connectionIds, cur.toolVisibility)
  }

  const addStepPlatformTool = (agentIndex: number, toolId: number) => {
    if (stepEffectiveToolVisibility(agentIndex) === 'none') return
    const cur = stepToolSelections[agentIndex] ?? { platformIds: [], connectionIds: [] }
    if (cur.platformIds.includes(toolId)) return
    setStepTools(agentIndex, [...cur.platformIds, toolId], cur.connectionIds, cur.toolVisibility)
  }

  const addStepConnection = (agentIndex: number, connId: number) => {
    if (stepEffectiveToolVisibility(agentIndex) === 'none') return
    const cur = stepToolSelections[agentIndex] ?? { platformIds: [], connectionIds: [] }
    if (cur.connectionIds.includes(connId)) return
    setStepTools(agentIndex, cur.platformIds, [...cur.connectionIds, connId], cur.toolVisibility)
  }

  const parseOutputContractForSave = (): Record<string, unknown> | null => {
    if (!showOutputContractBlock) return null
    const raw = outputContractText.trim()
    if (!raw) return { ...DEFAULT_OUTPUT_CONTRACT }
    try {
      const parsed = JSON.parse(raw) as unknown
      if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
        setError('Output contract must be a JSON object')
        return null
      }
      return parsed as Record<string, unknown>
    } catch {
      setError('Output contract must be valid JSON')
      return null
    }
  }

  const handleSaveOutputSettings = async () => {
    if (!showOutputContractBlock) {
      setError('Output contract block is not available for this job configuration.')
      return
    }
    const outputContract = parseOutputContractForSave()
    if (outputContract === null) return
    setIsLoading(true)
    setError('')
    try {
      await jobsAPI.update(jobId, {
        write_execution_mode: writeExecutionMode,
        output_artifact_format: outputArtifactFormat,
        output_contract: outputContract,
      })
      onWorkflowCreated()
    } catch (err: unknown) {
      const d = err as { response?: { data?: { detail?: string } } }
      setError(d.response?.data?.detail || 'Failed to save output settings')
    } finally {
      setIsLoading(false)
    }
  }

  const handleSuggestToolsFromBrd = async () => {
    if (workflowLocked) return
    if (selectedAgents.length === 0) {
      setError('Select at least one agent first')
      return
    }
    if (platformTools.length === 0) {
      setError('No platform tools in scope for this job — add job-level tools on the job or create MCP tools.')
      return
    }
    setIsLoading(true)
    setError('')
    try {
      const step_tool_visibility = selectedAgents.map((_, idx) => {
        const s = stepToolSelections[idx]
        return (s?.toolVisibility ?? jobToolVisibility) as ToolVisibility
      })
      const data = await jobsAPI.suggestWorkflowTools(jobId, selectedAgents, step_tool_visibility)
      if (data.detail && !(data.step_suggestions && data.step_suggestions.length)) {
        setError(data.detail)
        return
      }
      const base = stepToolSelectionsRef.current
      const next: StepToolSelection = { ...base }
      for (const s of data.step_suggestions || []) {
        const idx = s.agent_index
        const prev = base[idx] ?? { platformIds: [], connectionIds: [] }
        const effVis = prev.toolVisibility ?? jobToolVisibility
        if (effVis === 'none') {
          next[idx] = {
            platformIds: [],
            connectionIds: [],
            toolVisibility: 'none',
            ...(prev.taskType ? { taskType: prev.taskType } : {}),
          }
          continue
        }
        next[idx] = {
          platformIds: s.platform_tool_ids ?? [],
          connectionIds: prev.connectionIds,
          toolVisibility: prev.toolVisibility,
          ...(prev.taskType ? { taskType: prev.taskType } : {}),
        }
      }
      setStepToolSelections(next)
      if (data.output_contract_stub) {
        setOutputContractText(JSON.stringify(data.output_contract_stub, null, 2))
      }
    } catch (err: unknown) {
      const d = err as { response?: { data?: { detail?: string } } }
      setError(d.response?.data?.detail || 'Failed to suggest tools')
    } finally {
      setIsLoading(false)
    }
  }

  const handleAutoSplit = async () => {
    if (workflowLocked) {
      await handleSaveOutputSettings()
      return
    }
    if (selectedAgents.length === 0) {
      setError('Please select at least one agent')
      return
    }

    setIsLoading(true)
    setError('')
    try {
      let outputContract: Record<string, unknown> | undefined
      if (showOutputContractBlock) {
        const parsed = parseOutputContractForSave()
        if (parsed === null) {
          setIsLoading(false)
          return
        }
        outputContract = parsed
      }
      const workflowMode =
        workflowCollaboration === 'from_brd'
          ? undefined
          : workflowCollaboration === 'independent'
            ? 'independent'
            : 'sequential'
      // Read from ref so we always use the latest tool selections (avoids stale state when user clicks Create right after checking a box)
      const current = stepToolSelectionsRef.current
      const stepTools = selectedAgents.map((_, idx) => {
        const sel = current[idx]
        const effVis = sel?.toolVisibility ?? jobToolVisibility
        const slug = (sel?.taskType ?? '').trim().toLowerCase()
        const task_type = /^[a-z][a-z0-9_]{0,63}$/i.test(slug) ? slug : undefined
        if (effVis === 'none') {
          return {
            agent_index: idx,
            allowed_platform_tool_ids: [] as number[],
            allowed_connection_ids: [] as number[],
            tool_visibility: 'none' as const,
            ...(task_type ? { task_type } : {}),
          }
        }
        const hasPlatform = (sel?.platformIds?.length ?? 0) > 0
        const hasConn = (sel?.connectionIds?.length ?? 0) > 0
        // When only connections are selected, send empty platform list so backend does not inherit job-level platform tools
        const platformIds = hasPlatform ? sel!.platformIds : (hasConn ? [] : undefined)
        const connectionIds = hasConn ? sel!.connectionIds : (hasPlatform ? [] : undefined)
        return {
          agent_index: idx,
          allowed_platform_tool_ids: platformIds,
          allowed_connection_ids: connectionIds,
          tool_visibility: effVis,
          ...(task_type ? { task_type } : {}),
        }
      })
      // Always send step_tools when building a workflow so each step stores effective tool_visibility
      // (matches job dropdown). Backend merges omitted allowlists with job-level scope.
      const hasStepTools = selectedAgents.length > 0
      await jobsAPI.autoSplitWorkflow(
        jobId,
        selectedAgents,
        workflowMode,
        hasStepTools ? stepTools : undefined,
        jobToolVisibility,
        showOutputContractBlock
          ? {
              write_execution_mode: writeExecutionMode,
              output_artifact_format: outputArtifactFormat,
              output_contract: outputContract,
            }
          : undefined
      )
      onWorkflowCreated()
    } catch (err: any) {
      setError(err.response?.data?.detail || 'Failed to create workflow')
    } finally {
      setIsLoading(false)
    }
  }

  const toggleAgent = (agentId: number) => {
    setSelectedAgents((prev) =>
      prev.includes(agentId)
        ? prev.filter((id) => id !== agentId)
        : [...prev, agentId]
    )
  }

  /** Platform tool types that participate in reads/writes or job output — show output-contract UI (postgres was missing: old heuristic only matched substrings like "database"). */
  const toolTypesWithWriteFlowUi = new Set([
    'postgres', 'mysql', 'sqlserver', 'snowflake', 'databricks', 'bigquery',
    'vector_db', 'pinecone', 'weaviate', 'qdrant', 'chroma',
    'elasticsearch', 'pageindex',
    'filesystem', 's3', 'minio', 'ceph', 'azure_blob', 'gcs',
    'slack', 'github', 'notion', 'rest_api',
  ])
  const hasWriteCapablePlatformTools = platformTools.some((tool) => {
    const t = String(tool.tool_type || '').toLowerCase()
    if (toolTypesWithWriteFlowUi.has(t)) return true
    const n = String(tool.name || '').toLowerCase()
    return /postgres|mysql|sql|snowflake|databricks|bigquery|s3|minio|vector|chroma|pinecone|bucket|storage|warehouse/i.test(n)
  })
  const hasConnectionInScope =
    connections.length > 0 &&
    (
      selectedAgents.some((_, idx) => (stepToolSelections[idx]?.connectionIds?.length ?? 0) > 0) ||
      (!!job?.allowed_connection_ids && job.allowed_connection_ids.length > 0)
    )
  /** Selected per-step platform tools (narrow assignment) — if any are persistence-related, surface write UI */
  const selectedStepUsesWriteFlowTool = selectedAgents.some((_, idx) => {
    const ids = stepToolSelections[idx]?.platformIds ?? []
    return ids.some((id) => {
      const tool = platformTools.find((t) => t.id === id)
      if (!tool) return false
      const t = String(tool.tool_type || '').toLowerCase()
      return toolTypesWithWriteFlowUi.has(t)
    })
  })
  const showOutputContractBlock =
    hasWriteCapablePlatformTools || hasConnectionInScope || selectedStepUsesWriteFlowTool

  return (
    <div className="bg-dark-100/50 backdrop-blur-xl rounded-2xl shadow-2xl p-8 border border-dark-200/50">
      <div className="mb-6 p-5 bg-primary-500/10 border-2 border-primary-500/30 rounded-xl">
        <h3 className="font-bold text-primary-400 mb-2 text-base">Workflow mode</h3>
        <p className="text-sm text-white/70 font-medium mb-2">
          All agents are called over A2A by the platform. The badge below is about collaboration style, not transport.
        </p>
        <p className="text-sm text-white/90 font-medium">
          <strong>Sequential:</strong> Each agent receives the previous agent’s output (pipeline). Use agents without the A2A badge.
          <strong className="ml-1"> A2A:</strong> Agents collaborate asynchronously; choose agents with the &quot;A2A&quot; badge when your requirements need peer-to-peer collaboration.
        </p>
      </div>
      <div className="mb-6 p-5 bg-emerald-500/10 border-2 border-emerald-500/30 rounded-xl">
        <h3 className="font-bold text-emerald-400 mb-2 text-base">BRD &amp; Q&A → Auto-Split</h3>
        <p className="text-sm text-white/90 font-medium">
          Work is divided among agents based on your <strong>job prompt</strong> and <strong>BRD documents</strong>. Run <strong>Analyze Documents</strong> first so the AI can ask questions from your BRD; your answers are then used when splitting work. Each agent receives only its assigned subtask derived from the BRD and prompt.
        </p>
        <p className="text-sm text-white/80 font-medium mt-3 border-t border-emerald-500/30 pt-3">
          <strong className="text-emerald-300">Tools &amp; contracts (same inputs):</strong> Use{' '}
          <strong className="text-white">Suggest tools from BRD &amp; job</strong> below to propose which platform tools
          each step should see — search-heavy tools toward early steps, persistence (SQL / buckets) toward the last step.
          Badges show read vs write posture. The optional <strong className="text-white">output contract</strong> stub
          lists <code className="text-primary-300">write_targets</code> with <code className="text-primary-300">platform_&lt;id&gt;_…</code> names; edit buckets/prefixes/tables to match your configs.
        </p>
      </div>
      <div className="mb-8">
        <h2 className="text-4xl font-black text-white tracking-tight mb-6">Build Workflow</h2>
        <div className="flex gap-4 mb-6">
          <button
            onClick={() => setMode('auto')}
            className={`px-6 py-3.5 rounded-xl font-bold transition-all duration-200 ${
              mode === 'auto'
                ? 'bg-gradient-to-r from-primary-500 to-primary-700 text-white shadow-2xl shadow-primary-500/50 scale-105'
                : 'bg-dark-200/50 text-white/70 hover:text-white border border-dark-300'
            }`}
          >
            Auto-Split
          </button>
          <button
            onClick={() => setMode('manual')}
            className={`px-6 py-3.5 rounded-xl font-bold transition-all duration-200 ${
              mode === 'manual'
                ? 'bg-gradient-to-r from-primary-500 to-primary-700 text-white shadow-2xl shadow-primary-500/50 scale-105'
                : 'bg-dark-200/50 text-white/70 hover:text-white border border-dark-300'
            }`}
          >
            Manual Assignment
          </button>
        </div>
      </div>

      {error && (
        <div className="bg-red-500/20 border-2 border-red-500/50 text-red-400 px-6 py-4 rounded-2xl mb-6 font-semibold">
          {error}
        </div>
      )}

      {mode === 'auto' && (
        <div>
          {workflowLocked && (
            <div className="mb-6 p-4 bg-amber-500/15 border border-amber-500/40 rounded-xl text-amber-200/95 text-sm font-medium">
              This job is no longer in draft. The output contract and write mode below reflect your last saved values — update them and click{' '}
              <strong className="text-white">Save output &amp; write settings</strong>. Rebuilding the auto-split workflow is only available while the job is in draft.
            </div>
          )}
          <h3 className="font-black text-white mb-5 text-xl">Select Agents for Auto-Split</h3>
          <div className="mb-6">
            <label className="block text-sm font-bold text-white/90 mb-2">Agents work</label>
            <select
              value={workflowCollaboration}
              onChange={(e) => setWorkflowCollaboration(e.target.value as WorkflowCollaborationMode)}
              disabled={workflowLocked}
              className="px-4 py-2.5 bg-dark-200/80 border-2 border-dark-300 rounded-xl text-white font-medium focus:ring-2 focus:ring-primary-500 focus:border-primary-500 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <option value="from_brd">From BRD / document (default)</option>
              <option value="independent">Independently (each agent gets only its task)</option>
              <option value="sequential">Sequentially (each agent receives previous agent output)</option>
            </select>
            <p className="text-xs text-white/50 mt-1.5">
              {workflowCollaboration === 'independent' && 'Best when tasks are separate (e.g. 2+5 and 9-1).'}
              {workflowCollaboration === 'sequential' && 'Best when agent 2 needs agent 1’s result (pipeline).'}
              {workflowCollaboration === 'from_brd' && 'Uses analyze-documents hint from your BRD when available.'}
            </p>
            {independentSharedToolWarning && (
              <div
                className={`mt-4 p-4 rounded-xl border-2 text-sm ${
                  independentSharedToolWarning.variant === 'strong'
                    ? 'bg-amber-500/15 border-amber-500/50 text-amber-100'
                    : 'bg-slate-600/20 border-slate-400/40 text-white/90'
                }`}
                role="status"
              >
                <p className="font-bold text-white mb-2">{independentSharedToolWarning.title}</p>
                <ul className="list-disc list-inside space-y-1.5 text-white/85 leading-relaxed">
                  {independentSharedToolWarning.lines.map((line, i) => (
                    <li key={i}>{line}</li>
                  ))}
                </ul>
                <p className="mt-3 text-xs text-white/55">
                  Operations guide: repository file{' '}
                  <code className="text-primary-300 bg-dark-200/80 px-1 rounded">backend/docs/INDEPENDENT_WORKFLOW_SHARED_TOOLS.md</code>
                  — parallel execution, logging headers (<code className="text-primary-300">X-Sandhi-Trace-Id</code>, etc.).
                </p>
              </div>
            )}
            {workflowCollaboration === 'from_brd' && job?.allowed_platform_tool_ids && job.allowed_platform_tool_ids.length > 0 && (
              <p className="text-xs text-emerald-400/90 mt-1.5 font-medium">
                Job tools will be assigned to all agents automatically. You can optionally restrict tools per agent below.
              </p>
            )}
          </div>
          <div className="mb-6">
            <label className="block text-sm font-bold text-white/90 mb-2">Tool visibility (what agents see)</label>
            <select
              value={jobToolVisibility}
              onChange={(e) => setJobToolVisibility(e.target.value as ToolVisibility)}
              disabled={workflowLocked}
              className="px-4 py-2.5 bg-dark-200/80 border-2 border-dark-300 rounded-xl text-white font-medium focus:ring-2 focus:ring-primary-500 focus:border-primary-500 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <option value="full">Full — Names, descriptions, schema & business context</option>
              <option value="names_only">Names only — Tool names and short description; no schema or DB context</option>
              <option value="none">None — No tool list; agents cannot use MCP tools for this job</option>
            </select>
            <p className="text-xs text-white/50 mt-1.5">Credentials are never shared. This only controls how much tool metadata (names, schema, etc.) agents receive.</p>
          </div>
          <div className="space-y-3 max-h-80 overflow-y-auto border-2 border-dark-300 rounded-xl p-5 mb-6 bg-dark-200/30">
            {availableAgents.length === 0 ? (
              <p className="text-white/50 text-center py-8 font-medium">No agents available</p>
            ) : (
              availableAgents.map((agent) => (
                <label
                  key={agent.id}
                  className="flex items-center space-x-4 cursor-pointer hover:bg-dark-200/50 p-4 rounded-xl transition-colors border border-transparent hover:border-primary-500/30"
                >
                  <input
                    type="checkbox"
                    checked={selectedAgents.includes(agent.id)}
                    onChange={() => toggleAgent(agent.id)}
                    disabled={workflowLocked}
                    className="w-5 h-5 text-primary-600 bg-dark-200 border-dark-300 rounded focus:ring-primary-500 focus:ring-2 disabled:opacity-50 disabled:cursor-not-allowed"
                  />
                  <div className="flex-1">
                    <div className="flex items-center gap-2 flex-wrap">
                      <span className="font-bold text-white text-lg">{agent.name}</span>
                      {agent.a2a_enabled && (
                        <span className="px-2 py-0.5 text-xs font-bold bg-primary-500/30 text-primary-300 rounded border border-primary-500/50">
                          A2A
                        </span>
                      )}
                    </div>
                    <div className="text-sm text-primary-400 font-semibold mt-1">
                      ${agent.price_per_task.toFixed(2)} per task
                    </div>
                  </div>
                </label>
              ))
            )}
          </div>
          {(platformTools.length > 0 || connections.length > 0) && selectedAgents.length > 0 && !workflowLocked && (
            <div className="mb-6 p-5 bg-emerald-500/10 border-2 border-emerald-500/30 rounded-xl">
              <div className="flex flex-wrap items-center justify-between gap-3 mb-3">
                <h4 className="font-bold text-emerald-400">Tools per agent (optional)</h4>
                <button
                  type="button"
                  onClick={handleSuggestToolsFromBrd}
                  disabled={isLoading || platformTools.length === 0}
                  className="px-4 py-2 rounded-lg text-sm font-bold bg-emerald-600/80 text-white hover:bg-emerald-500 disabled:opacity-50 disabled:cursor-not-allowed border border-emerald-400/40"
                >
                  Suggest tools from BRD &amp; job
                </button>
              </div>
              <p className="text-sm text-white/70 mb-4">
                {jobHasExplicitMcpScope(job) ? (
                  <>
                    Add only the tools each agent can use. If you leave a step empty, it uses the{' '}
                    <strong className="text-white/90">job&rsquo;s selected tools</strong> only.
                  </>
                ) : (
                  <>
                    Add only the tools each agent can use. With no job-level tool selection yet, a step you leave empty shows{' '}
                    <strong className="text-white/90">no tools</strong> here — pick tools per step or restrict tools when creating the job.
                  </>
                )}{' '}
                Suggestions use the same BRD excerpts and Q&amp;A as task splitting (first selected agent = splitter API).
              </p>
              <div className="mb-4 p-4 rounded-xl bg-dark-100/80 border border-dark-300 text-sm text-white/85 space-y-2">
                <p className="font-semibold text-white">How reads and writes work</p>
                <ul className="list-disc list-inside space-y-1 text-white/75">
                  <li>
                    <strong className="text-white/90">During the step</strong>, the agent calls selected MCP tools (e.g. SQL via <code className="text-primary-300">query</code> for Postgres). That is <strong className="text-white/90">interactive</strong> tool use.
                  </li>
                  <li>
                    <strong className="text-white/90">Final job output</strong> (writing workflow results to DB, object storage, etc.) is configured in <strong className="text-white/90">Output contract and write mode</strong> below — not by picking tools here alone.
                  </li>
                  <li>
                    <strong className="text-white/90">Who writes</strong>: choose <strong>Platform</strong> (orchestrator runs write tools from the artifact) vs <strong>Agent</strong> (the model calls write tools). That appears in the section below when your job has write-capable tools or connections.
                  </li>
                </ul>
              </div>
              <div className="space-y-4">
                {selectedAgents.map((agentId, idx) => {
                  const agent = availableAgents.find((a) => a.id === agentId)
                  const sel = stepToolSelections[idx] ?? { platformIds: [], connectionIds: [] }
                  const effVis = sel.toolVisibility ?? jobToolVisibility
                  const selectedPlatformTools = platformTools.filter((t) => sel.platformIds.includes(t.id))
                  const selectedConns = connections.filter((c) => sel.connectionIds.includes(c.id))
                  const availableToAddPlatform = platformTools.filter((t) => !sel.platformIds.includes(t.id))
                  const availableToAddConn = connections.filter((c) => !sel.connectionIds.includes(c.id))
                  const showToolAssignment = effVis !== 'none'
                  const hasAnySelected =
                    showToolAssignment && (selectedPlatformTools.length > 0 || selectedConns.length > 0)
                  return (
                    <div key={agentId} className="border border-dark-300 rounded-lg p-4 bg-dark-200/30">
                      <div className="font-bold text-white mb-2">Step {idx + 1}: {agent?.name ?? `Agent ${agentId}`}</div>
                      <div className="mb-3">
                        <label className="text-xs text-white/70 mr-2">Step tool visibility:</label>
                        <select
                          value={effVis}
                          onChange={(e) => {
                            const v = e.target.value as ToolVisibility
                            if (v === 'none') {
                              setStepTools(idx, [], [], v)
                            } else {
                              setStepTools(idx, sel.platformIds, sel.connectionIds, v)
                            }
                          }}
                          className="px-2 py-1 bg-dark-200/80 border border-dark-300 rounded text-white text-sm min-w-[200px]"
                          title="Full = names, descriptions, schema. Names only = names + short description. None = no tools."
                        >
                          <option value="full">Full (schema + context)</option>
                          <option value="names_only">Names only (no schema)</option>
                          <option value="none">None (no tools)</option>
                        </select>
                      </div>
                      <div className="mb-3">
                        <label className="block text-xs text-white/70 mb-1">
                          Task type slug (optional — tool assignment registry)
                        </label>
                        <input
                          type="text"
                          value={sel.taskType ?? ''}
                          onChange={(e) =>
                            setStepTools(
                              idx,
                              effVis === 'none' ? [] : sel.platformIds,
                              effVis === 'none' ? [] : sel.connectionIds,
                              sel.toolVisibility,
                              { taskType: e.target.value }
                            )
                          }
                          placeholder="e.g. search, persist"
                          className="w-full max-w-md px-3 py-2 bg-dark-200/80 border border-dark-300 rounded-lg text-white text-sm placeholder:text-white/35 focus:ring-2 focus:ring-primary-500 focus:border-primary-500"
                          title="Letter, then letters, digits, or underscores (max 64 chars). Invalid values are omitted when creating the workflow."
                        />
                      </div>
                      <div className="space-y-2">
                        <div className="text-sm font-semibold text-white/90">Selected for this step:</div>
                        {!showToolAssignment ? (
                          <p className="text-xs text-white/60">
                            No tools for this step — visibility is set to None (no MCP tools).
                          </p>
                        ) : !hasAnySelected ? (
                          jobHasExplicitMcpScope(job) ? (
                            <p className="text-xs text-white/50 italic">
                              No tools selected for this step — uses the job&rsquo;s tool list.
                            </p>
                          ) : (
                            <p className="text-xs text-white/45 tabular-nums" aria-label="No tools selected">
                              —
                            </p>
                          )
                        ) : (
                          <div className="flex flex-wrap gap-3">
                            {selectedPlatformTools.map((t) => {
                              const access = getToolAccessBadge(t.tool_type)
                              return (
                                <div
                                  key={t.id}
                                  className="flex min-w-[220px] max-w-full flex-col gap-1.5 rounded-xl border border-primary-500/45 bg-dark-50/95 px-3 py-2.5 shadow-inner shadow-black/30"
                                >
                                  <div className="flex items-start justify-between gap-2">
                                    <div className="min-w-0 flex-1">
                                      <div className="truncate text-sm font-bold text-white" title={t.name}>
                                        {t.name}
                                      </div>
                                      <div className="mt-1 flex flex-wrap items-center gap-2">
                                        <span className="text-[10px] font-semibold uppercase tracking-wide text-white/45">
                                          Access
                                        </span>
                                        <span
                                          className="max-w-[200px] truncate rounded-md bg-emerald-600 px-2 py-1 text-[11px] font-semibold leading-snug text-white shadow-sm ring-1 ring-emerald-400/40"
                                          title={access.hint}
                                        >
                                          {access.label}
                                        </span>
                                      </div>
                                      <div className="mt-0.5 text-[10px] font-mono text-dark-500" title="Platform tool type">
                                        {t.tool_type}
                                      </div>
                                    </div>
                                    <button
                                      type="button"
                                      onClick={() => toggleStepPlatformTool(idx, t.id)}
                                      className="shrink-0 rounded-md px-2 py-0.5 text-lg leading-none text-white/60 transition hover:bg-white/10 hover:text-white focus:outline-none focus:ring-2 focus:ring-primary-400"
                                      aria-label={`Remove ${t.name}`}
                                    >
                                      <span className="sr-only">Remove</span>×
                                    </button>
                                  </div>
                                </div>
                              )
                            })}
                            {selectedConns.map((c) => (
                              <span
                                key={c.id}
                                className="inline-flex items-center gap-1.5 px-2.5 py-1 bg-primary-500/20 border border-primary-500/50 rounded-lg text-sm text-white"
                              >
                                <span className="truncate max-w-[120px]">{c.name}</span>
                                <button
                                  type="button"
                                  onClick={() => toggleStepConnection(idx, c.id)}
                                  className="text-white/70 hover:text-white focus:outline-none"
                                  aria-label={`Remove ${c.name}`}
                                >
                                  <span className="sr-only">Remove</span>×
                                </button>
                              </span>
                            ))}
                          </div>
                        )}
                        {showToolAssignment &&
                          (availableToAddPlatform.length > 0 || availableToAddConn.length > 0) && (
                          <div className="flex flex-wrap items-center gap-2 pt-1">
                            <span className="text-xs text-white/70">Add tool:</span>
                            {availableToAddPlatform.length > 0 && (
                              <select
                                value=""
                                onChange={(e) => {
                                  const id = Number(e.target.value)
                                  if (id) addStepPlatformTool(idx, id)
                                  e.target.value = ''
                                }}
                                className="px-2 py-1 bg-dark-200/80 border border-dark-300 rounded text-white text-sm"
                              >
                                <option value="">— Platform tool —</option>
                                {availableToAddPlatform.map((t) => (
                                  <option key={t.id} value={t.id}>
                                    {t.name} — {getToolAccessBadge(t.tool_type).label}
                                  </option>
                                ))}
                              </select>
                            )}
                            {availableToAddConn.length > 0 && (
                              <select
                                value=""
                                onChange={(e) => {
                                  const id = Number(e.target.value)
                                  if (id) addStepConnection(idx, id)
                                  e.target.value = ''
                                }}
                                className="px-2 py-1 bg-dark-200/80 border border-dark-300 rounded text-white text-sm"
                              >
                                <option value="">— Connection —</option>
                                {availableToAddConn.map((c) => (
                                  <option key={c.id} value={c.id}>{c.name}</option>
                                ))}
                              </select>
                            )}
                          </div>
                        )}
                      </div>
                    </div>
                  )
                })}
              </div>
            </div>
          )}
          {showOutputContractBlock && (
            <div className="mb-6 p-5 bg-indigo-500/10 border-2 border-indigo-500/30 rounded-xl">
              <h4 className="font-bold text-indigo-300 mb-2">Output contract and write mode</h4>
              <p className="text-sm text-white/70 mb-3">
                Default is Sandhi AI universal JSON contract. You can customize this when your job uses MCP write tools.
              </p>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-3">
                <div>
                  <label className="block text-white/80 text-sm font-semibold mb-1">Write execution mode</label>
                  <select
                    value={writeExecutionMode}
                    onChange={(e) =>
                      setWriteExecutionMode(e.target.value as 'platform' | 'agent' | 'ui_only')
                    }
                    className="px-4 py-2.5 bg-dark-200/80 border-2 border-dark-300 rounded-xl text-white font-medium focus:ring-2 focus:ring-primary-500 focus:border-primary-500 w-full"
                  >
                    <option value="platform">Platform triggers write tools from artifact reference</option>
                    <option value="agent">AI agent triggers write tools from artifact reference</option>
                    <option value="ui_only">UI only — show results in app; no artifact file or contract writes</option>
                  </select>
                </div>
                <div>
                  <label className="block text-white/80 text-sm font-semibold mb-1">Output artifact format</label>
                  <select
                    value={outputArtifactFormat}
                    onChange={(e) => setOutputArtifactFormat(e.target.value as 'jsonl' | 'json')}
                    className="px-4 py-2.5 bg-dark-200/80 border-2 border-dark-300 rounded-xl text-white font-medium focus:ring-2 focus:ring-primary-500 focus:border-primary-500 w-full"
                  >
                    <option value="jsonl">JSONL (best for bulk and high volume)</option>
                    <option value="json">JSON (single structured payload)</option>
                  </select>
                </div>
              </div>
              <textarea
                value={outputContractText}
                onChange={(e) => setOutputContractText(e.target.value)}
                rows={10}
                className="w-full px-4 py-3 bg-dark-200/80 border-2 border-dark-300 rounded-xl text-white font-mono text-sm focus:ring-2 focus:ring-primary-500 focus:border-primary-500"
                placeholder="Paste output contract JSON"
              />
            </div>
          )}
          <button
            onClick={handleAutoSplit}
            disabled={
              isLoading ||
              (!workflowLocked && selectedAgents.length === 0) ||
              (workflowLocked && !showOutputContractBlock)
            }
            className="bg-gradient-to-r from-primary-500 to-primary-700 text-white px-8 py-4 rounded-xl font-bold hover:shadow-2xl hover:shadow-primary-500/50 hover:scale-105 transition-all duration-200 disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:scale-100"
          >
            {isLoading ? (
              <span className="flex items-center gap-2">
                <div className="animate-spin rounded-full h-5 w-5 border-2 border-white border-t-transparent"></div>
                {workflowLocked ? 'Saving...' : 'Creating...'}
              </span>
            ) : workflowLocked ? (
              'Save output & write settings'
            ) : (
              'Create Auto-Split Workflow'
            )}
          </button>
        </div>
      )}

      {mode === 'manual' && (
        <div>
          <p className="text-white/60 text-lg font-medium mb-4">
            Manual workflow assignment coming soon...
          </p>
        </div>
      )}
    </div>
  )
}
